name: storybook
description: A storybook for a collection of widget.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  google_fonts: ^4.0.3
  digit_ui_components: ^0.0.1+7
  inspector: 2.1.0
  flutter_svg: ^2.0.10+1
  storybook_toolkit: ^1.3.2
  universal_html: ^2.2.4
  flutter_styled_toast: ^2.2.1
  doc_widget: 0.4.0
  url_launcher: ^6.1.14


dev_dependencies:
  flutter_test:
    sdk: flutter
  doc_widget_annotation: ^0.2.8
  doc_widget_builder: ^0.4.0
 # flutter_lints: 2.0.3


flutter:
  assets:
    - assets/images/
    - assets/icons/svg/
    - assets/animated_json/
    - assets/localized_data.json

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
    - family: Roboto Condensed
      fonts:
        - asset: assets/fonts/Roboto/RobotoCondensed-Regular.ttf

  uses-material-design: true
