name: Node.js Publish UI CSS Packages

on:
  push:
    branches: [ 'develop-webpack' ]
    paths:
      - 'webpack/css/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: yarn && yarn build && npm publish --tag core-v0.1
        working-directory: ./webpack/css/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
